import { z } from 'zod';

/**
 * The current on-disk workspace config version. Every config-building
 * call site (ipc/handlers.ts's restoreWorkspace and createWorkspace)
 * uses this instead of repeating the literal `1`, so a future version
 * bump (Tier 2 migration, docs/architecture.md #3) means changing this
 * one value plus adding explicit migration logic — not hunting down
 * every hardcoded `1` across the codebase.
 */
export const CURRENT_WORKSPACE_CONFIG_VERSION = 1 as const;

/**
 * A single workspace step: a tool type plus its (tool-specific) params.
 * `params` is intentionally untyped here — each tool module owns and
 * validates its own params schema (docs/architecture.md #2, Plugin-
 * Style Tool Registry). This envelope only guarantees "some tool type,
 * some params object" is present before handing off to that tool's own
 * `validate()`.
 */
export const WorkspaceStepSchema = z.object({
  type: z.string().min(1),
  params: z.record(z.string(), z.unknown()),
});

export type WorkspaceStep = z.infer<typeof WorkspaceStepSchema>;

/**
 * A full workspace config, as saved to disk. `version` is required from
 * day one (docs/architecture.md #3) so a future schema change can branch
 * on it and migrate, instead of silently breaking old configs.
 */
export const WorkspaceConfigSchema = z.object({
  version: z.literal(CURRENT_WORKSPACE_CONFIG_VERSION),
  // Restricted to a safe filename-token charset (letters, digits,
  // hyphens, underscores — randomUUID() output stays well within this)
  // because config/loader.ts uses `id` directly as `<id>.json` when
  // reading/writing/deleting on disk. Today createWorkspace always
  // generates `id` itself via randomUUID(), so this isn't reachable
  // through the app's own IPC surface — but a hand-placed or
  // future-imported config file isn't bound by that, and an id like
  // "../../../Library/LaunchAgents/evil" would otherwise let a save or
  // delete escape the intended workspaces directory. Defense in depth,
  // enforced once here rather than at every call site.
  id: z
    .string()
    .min(1)
    .regex(/^[A-Za-z0-9_-]+$/, 'id must contain only letters, numbers, hyphens, and underscores'),
  name: z.string().min(1),
  steps: z.array(WorkspaceStepSchema),
});

export type WorkspaceConfig = z.infer<typeof WorkspaceConfigSchema>;

export type WorkspaceConfigParseResult =
  { success: true; config: WorkspaceConfig } | { success: false; error: string };

/**
 * Parses and validates untrusted input (a workspace config read from
 * disk) into a WorkspaceConfig. Never throws — config files are
 * untrusted input that gets shelled out against downstream, so a
 * malformed or malicious file must fail loudly and safely here, not
 * crash the app or silently coerce into something unintended.
 */
export function parseWorkspaceConfig(input: unknown): WorkspaceConfigParseResult {
  const result = WorkspaceConfigSchema.safeParse(input);
  if (!result.success) {
    return { success: false, error: result.error.message };
  }
  return { success: true, config: result.data };
}

/**
 * What the renderer sends to create a new workspace. `id` and `version`
 * are deliberately excluded — they're generated by the main process
 * (see ipc/handlers.ts's createWorkspace), never user input, so there's
 * no way for a caller to supply a wrong or colliding one.
 */
export interface CreateWorkspaceInput {
  name: string;
  steps: WorkspaceStep[];
}

/**
 * Mirrors WorkspaceConfigParseResult's shape/spirit: a flat,
 * discriminated success/failure result instead of a thrown exception,
 * because "the user left a required field empty" is routine input
 * during normal use of the Save button, not an exceptional condition.
 */
export type CreateWorkspaceResult =
  { success: true; config: WorkspaceConfig } | { success: false; error: string };

/**
 * What the renderer sends to update an existing workspace. Unlike
 * CreateWorkspaceInput, `id` is required — it identifies which saved
 * config to overwrite (ipc/handlers.ts's updateWorkspace, via
 * config/loader.ts's saveWorkspaceConfig — already an overwrite-by-id
 * primitive, unchanged by this feature). `version` stays excluded and
 * server-regenerated, same reasoning as CreateWorkspaceInput.
 */
export interface UpdateWorkspaceInput {
  id: string;
  name: string;
  steps: WorkspaceStep[];
}

/** Mirrors CreateWorkspaceResult's exact shape/spirit. */
export type UpdateWorkspaceResult =
  { success: true; config: WorkspaceConfig } | { success: false; error: string };

/**
 * Mirrors CreateWorkspaceResult/UpdateWorkspaceResult's shape, minus a
 * payload — a successful delete has nothing further to hand back
 * beyond "it's gone."
 */
export type DeleteWorkspaceResult = { success: true } | { success: false; error: string };
